### PR TITLE
shahresume.txt

### PR DESCRIPTION
**Pull request by shahnok007**

### CODE REVIEW

**Comment by avinash201199** [comment]
please add pdf or doc file

**Comment by shahnok007** [comment]
upload file option is disabled

**Comment by shahnok007** [comment]
[SHAHNAWAZ's Resume.pdf](https://github.com/avinash201199/Resume-Templates/files/9769205/SHAHNAWAZ.s.Resume.pdf)

**Comment by avinash201199** [comment]
not here , please read contributing.mf file to contribute

**Pull request closed without merging**
